import { Save } from "lucide-react";
import { useEffect, useState } from "react";
import type { AppSettings, CharacterPreset, PosePreset, PresetDocument, StylePreset } from "../../../src/index.ts";
import { ModelField, TokenField } from "../components/TokenField";

function SaveBar({ onSave, status }: { onSave: () => void; status: string }) { return <div className="save-bar"><span>{status}</span><button className="primary" onClick={onSave}><Save size={15}/>Save changes</button></div>; }
const NumberField = ({ label, value, onChange, step = 0.05 }: { label: string; value: number; onChange: (value: number) => void; step?: number }) => <label className="field"><span>{label}</span><input type="number" step={step} value={value} onChange={(e) => onChange(Number(e.target.value))}/></label>;

export function CharactersPage({ document, loras, save }: { document: PresetDocument<CharacterPreset>; loras: string[]; save: (doc: PresetDocument<CharacterPreset>) => Promise<void> }) {
  const first = Object.values(document.records)[0]; const [draft, setDraft] = useState(first); const [status, setStatus] = useState(""); useEffect(() => setDraft(first), [first]);
  if (!draft) return <Empty title="Characters"/>; const update = (next: Partial<CharacterPreset>) => setDraft({ ...draft, ...next });
  return <Editor title="Characters" intro="Character identity, appearance, LoRA, and costume presets."><div className="form-grid"><label className="field"><span>Preset ID</span><input value={draft.id} onChange={(e) => update({ id: e.target.value })}/></label><ModelField label="Character LoRA" value={draft.characterLora.fileName} options={loras} onChange={(fileName) => update({ characterLora: { ...draft.characterLora, fileName } })}/><NumberField label="Model strength" value={draft.characterLora.strengthModel} onChange={(strengthModel) => update({ characterLora: { ...draft.characterLora, strengthModel } })}/><NumberField label="CLIP strength" value={draft.characterLora.strengthClip} onChange={(strengthClip) => update({ characterLora: { ...draft.characterLora, strengthClip } })}/></div><TokenField label="Trigger terms" value={draft.characterLora.trigger} onChange={(trigger) => update({ characterLora: { ...draft.characterLora, trigger } })}/><TokenField label="Identity" value={draft.female.identity} onChange={(identity) => update({ female: { ...draft.female, identity } })}/><TokenField label="Appearance" value={draft.female.appearance} onChange={(appearance) => update({ female: { ...draft.female, appearance } })}/><h2>Costumes</h2>{Object.values(draft.costumes).map((costume) => <div className="inline-panel" key={costume.id}><strong>{costume.id}</strong><TokenField label="Costume terms" value={costume.costume} onChange={(terms) => update({ costumes: { ...draft.costumes, [costume.id]: { ...costume, costume: terms } } })}/></div>)}<SaveBar status={status} onSave={async () => { await save({ version: 1, records: { ...document.records, [draft.id]: draft } }); setStatus("Saved"); }}/></Editor>;
}

export function StylesPage({ document, loras, save }: { document: PresetDocument<StylePreset>; loras: string[]; save: (doc: PresetDocument<StylePreset>) => Promise<void> }) {
  const first = Object.values(document.records)[0]; const [draft, setDraft] = useState(first); useEffect(() => setDraft(first), [first]); if (!draft) return <Empty title="Styles"/>;
  return <Editor title="Styles" intro="Style prompt terms and optional LoRA configuration."><div className="form-grid"><label className="field"><span>Preset ID</span><input value={draft.id} onChange={(e) => setDraft({ ...draft, id: e.target.value })}/></label><ModelField label="Style LoRA" value={draft.styleLora?.fileName ?? ""} options={loras} onChange={(fileName) => setDraft({ ...draft, styleLora: { fileName, strengthModel: draft.styleLora?.strengthModel ?? .6, strengthClip: draft.styleLora?.strengthClip ?? .6, trigger: draft.styleLora?.trigger ?? [] } })}/></div><TokenField label="Style terms" value={draft.style} onChange={(style) => setDraft({ ...draft, style })}/><TokenField label="LoRA triggers" value={draft.styleLora?.trigger ?? []} onChange={(trigger) => setDraft({ ...draft, styleLora: { fileName: draft.styleLora?.fileName ?? "", strengthModel: draft.styleLora?.strengthModel ?? .6, strengthClip: draft.styleLora?.strengthClip ?? .6, trigger } })}/><SaveBar status="" onSave={() => save({ version: 1, records: { ...document.records, [draft.id]: draft } })}/></Editor>;
}

export function PosesPage({ document, loras, controlnets, images, save }: { document: PresetDocument<PosePreset>; loras: string[]; controlnets: string[]; images: string[]; save: (doc: PresetDocument<PosePreset>) => Promise<void> }) {
  const first = Object.values(document.records)[0]; const [draft, setDraft] = useState(first); useEffect(() => setDraft(first), [first]); if (!draft) return <Empty title="Poses"/>; const interaction = (key: keyof PosePreset["interaction"], value: string[]) => setDraft({ ...draft, interaction: { ...draft.interaction, [key]: value } });
  return <Editor title="Poses" intro="Subject layout, interaction, pose LoRA, and ControlNet."><div className="form-grid"><ModelField label="Pose LoRA" value={draft.poseLora.fileName} options={loras} onChange={(fileName) => setDraft({ ...draft, poseLora: { ...draft.poseLora, fileName } })}/><NumberField label="Male count" step={1} value={draft.subjectLayout.maleCount} onChange={(maleCount) => setDraft({ ...draft, subjectLayout: { femaleCount: 1, maleCount, totalSubjects: maleCount + 1 } })}/></div><TokenField label="Female to males" value={draft.interaction.femaleToMales} onChange={(v) => interaction("femaleToMales", v)}/><TokenField label="Males to female" value={draft.interaction.malesToFemale} onChange={(v) => interaction("malesToFemale", v)}/><TokenField label="Main pose" value={draft.interaction.mainPose} onChange={(v) => interaction("mainPose", v)}/><TokenField label="Spatial composition" value={draft.interaction.spatialComposition} onChange={(v) => interaction("spatialComposition", v)}/><div className="form-grid"><ModelField label="ControlNet model" value={draft.openPose?.controlNetModel ?? ""} options={controlnets} onChange={(controlNetModel) => setDraft({ ...draft, openPose: { ...draft.openPose!, controlNetModel } })}/><ModelField label="Reference image" value={draft.openPose?.referenceImagePath ?? ""} options={images} onChange={(referenceImagePath) => setDraft({ ...draft, openPose: { ...draft.openPose!, referenceImagePath } })}/><label className="field"><span>Preprocessor mode</span><select value={draft.openPose?.preprocessorMode} onChange={(e) => setDraft({ ...draft, openPose: { ...draft.openPose!, preprocessorMode: e.target.value as any } })}><option>bypass</option><option>full</option><option>body_only</option><option>face_only</option></select></label></div><SaveBar status="" onSave={() => save({ version: 1, records: { ...document.records, [draft.id]: draft } })}/></Editor>;
}

export function SettingsPage({ settings, checkpoints, save }: { settings: AppSettings; checkpoints: string[]; save: (settings: AppSettings) => Promise<void> }) {
  const [draft, setDraft] = useState(settings); useEffect(() => setDraft(settings), [settings]);
  const generation = (patch: Partial<AppSettings["generationDefaults"]>) => setDraft({ ...draft, generationDefaults: { ...draft.generationDefaults, ...patch } });
  return <Editor title="Settings" intro="Local ComfyUI connection, model, output, and generation defaults."><div className="form-grid">
    <label className="field"><span>ComfyUI URL</span><input value={draft.comfyUrl} onChange={(e) => setDraft({ ...draft, comfyUrl: e.target.value })}/></label><label className="field"><span>ComfyUI root</span><input value={draft.comfyRoot} onChange={(e) => setDraft({ ...draft, comfyRoot: e.target.value })}/></label>
    <ModelField label="Checkpoint" value={draft.checkpointName} options={checkpoints} onChange={(checkpointName) => setDraft({ ...draft, checkpointName })}/><label className="field"><span>Workflow filename</span><input value={draft.workflowFileName} onChange={(e) => setDraft({ ...draft, workflowFileName: e.target.value })}/></label><label className="field"><span>Output prefix</span><input value={draft.filenamePrefix} onChange={(e) => setDraft({ ...draft, filenamePrefix: e.target.value })}/></label>
    <NumberField label="Width" step={64} value={draft.generationDefaults.width} onChange={(width) => generation({ width })}/><NumberField label="Height" step={64} value={draft.generationDefaults.height} onChange={(height) => generation({ height })}/><NumberField label="Steps" step={1} value={draft.generationDefaults.steps} onChange={(steps) => generation({ steps })}/><NumberField label="CFG" value={draft.generationDefaults.cfg} onChange={(cfg) => generation({ cfg })}/>
    <label className="field"><span>Sampler</span><input value={draft.generationDefaults.sampler} onChange={(e) => generation({ sampler: e.target.value })}/></label><label className="field"><span>Scheduler</span><input value={draft.generationDefaults.scheduler} onChange={(e) => generation({ scheduler: e.target.value })}/></label>
  </div><SaveBar status="" onSave={() => save(draft)}/></Editor>;
}

function Editor({ title, intro, children }: { title: string; intro: string; children: React.ReactNode }) { return <main className="workspace"><header><h1>{title}</h1><p>{intro}</p></header>{children}</main>; }
function Empty({ title }: { title: string }) { return <Editor title={title} intro="No presets yet."><div className="empty-state">Create a preset document to begin.</div></Editor>; }
